### ISSUE TITLE
Small sugestion

### ISSUE THREAD

**Issue by JuanSalazar22** [jadarve/gpac_experiments#1]
Awesome collection, since it looks like you don't manage different version for the containers you could build them in the docker-compose, this way you can launch only the `docker-compose build` command and your images will be updated, additionally you can create images with different names per experiment using the same containers (e.g. in case you want to create an image with an specific version of gpac for one experiment).

```yaml
services:
  gstreamer:
    container_name: gstreamer
    build:
      context: .
      dockerfile: ../containers/gstreamer.dockerfile
    image: pac_experiments:gstreamer
```
